#?????? ?? ??
server:
  port: 80

#MYSQL ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #???? ?? ?? ??
        show_sql: true
        #???? ???? ??? ???? ?? ???
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true
#Thymeleaf cache 사용 중기
  thymeleaf:
    cache: false

#??? ???? ???? ??? ???? ??
logging:
  level:
#    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

